name: Android CI

on:
  push:
    branches: [ maiar ]
  pull_request:
    branches: [ maiar ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install system dependencies
      run: brew install boost ninja
    - name: Install Android Dependencies
      run: |
        tools/install-android-dependencies
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v1.1.2
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Run test
      run: |
        tools/generate-files
        tools/android-test
        tools/android-build
    - name: List build
      run: |
        ls -1 -R build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tw-maiar-android.aar
        path: build/trustwalletcore.aar
