name: Android Build

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest-large
    if: false
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Install system dependencies
      run: |
        tools/install-sys-dependencies-mac

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          rust

    - name: Install Rust dependencies
      run: |
        tools/install-rust-dependencies

    - name: Install Android Dependencies
      run: tools/install-android-dependencies

    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v3
      with:
        path: build/local
        key: ${{ runner.os }}-${{ runner.arch }}-internal-${{ hashFiles('tools/install-dependencies') }}-${{ hashFiles('tools/dependencies-version') }}

    - name: Install internal dependencies
      run: tools/install-dependencies
      if: steps.internal_cache.outputs.cache-hit != 'true'

    - name: Generate files
      run: tools/generate-files android

    - name: Build Kotlin doc
      run: tools/kotlin-doc

    - name: Build artifacts
      run: tools/android-build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wallet-core.aar
        path: build/wallet-core.aar
