name: iOS CI

on:
  workflow_dispatch:
  push:
    branches: [ maiar* ]
  pull_request:
    branches: [ maiar* ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        brew install boost ninja xcodegen xcbeautify
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v1.1.2
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Run codegen tests
      run: tools/codegen-test
    - name: Run iOS tests
      run: |
        tools/generate-files
        tools/ios-test
        tools/ios-build
    - name: List build
      run: |
        ls -1 -R build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tw-maiar-ios
        path: build/ios-frameworks
