name: iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest-xl
    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: |
        tools/install-sys-dependencies-mac
        tools/install-rust-dependencies
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v3
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Run codegen tests
      run: tools/codegen-test

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          rust

    - name: Generate files
      run: tools/generate-files

    - name: Build artifacts
      run: tools/ios-build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-frameworks.tar.gz
        path: build/ios-frameworks.tar.gz
