name: Kotlin CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.0.2

    - name: Install system dependencies
      run: |
        tools/install-sys-dependencies-mac
        tools/install-rust-dependencies

    - name: Install Kotlin Dependencies
      run: tools/install-kotlin-dependencies

    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v3
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}

    - name: Install internal dependencies
      run: tools/install-dependencies
      if: steps.internal_cache.outputs.cache-hit != 'true'

    - name: Generate files
      run: tools/generate-files

    - name: Build Kotlin Multiplatform
      run: tools/kotlin-build

    - name: Build KMP Sample
      run: ./gradlew assemble
      working-directory: samples/kmp
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
